# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify


def set_slugs(apps, schema_editor):
    for tag in apps.get_model('blog', 'Tag').objects.all():
        tag.slug = slugify(tag.name)
        tag.save()

    for category in apps.get_model('blog', 'Category').objects.all():
        category.slug = slugify(category.name)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Slug of the tag, used for URLs', unique=False, db_index=False, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Slug of the category, used for URLs', unique=False, db_index=False, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_slugs),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Slug of the tag, used for URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Slug of the category, used for URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Slug of the tag, used for URLs', unique=True),
        ),
    ]
