# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='author',
            name='static_photo',
            field=models.CharField(blank=True, help_text='Direct link to a JPG image, recommended size: 350px wide', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Image from the archive', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Image'),
        ),
    ]
