# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-23 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import djangoplicity.archives.translation
import djangoplicity.translation.fields
import djangoplicity.translation.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170914_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Post translation',
                'proxy': True,
                'indexes': [],
            },
            bases=('blog.post', djangoplicity.archives.translation.TranslationProxyMixin),
            managers=[
                ('translation_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='lang',
            field=djangoplicity.translation.fields.LanguageField(db_index=True, default=djangoplicity.translation.models._get_defaut_lang, max_length=7, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='blog.Post', verbose_name='Translation source'),
        ),
        migrations.AddField(
            model_name='post',
            name='translation_ready',
            field=models.BooleanField(default=False, help_text='When you check this box and save this translation, an automatic notification email will be sent.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Used for the URL, this cannot be updated later', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
