# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-04 19:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210223_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authors',
            field=djangoplicity.translation.fields.TranslationManyToManyField(through='blog.AuthorDescription', to='blog.Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=djangoplicity.translation.fields.TranslationForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Image', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=djangoplicity.translation.fields.TranslationForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=djangoplicity.translation.fields.TranslationManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
