# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210304_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.TextField(blank=True),
        ),
    ]
