# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210317_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='biography_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
