# Generated by Django 3.1 on 2022-09-12 21:07

from django.db import migrations, models
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0032_auto_20220803_1204'),
        ('blog', '0009_auto_20211109_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Image from the archive', null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=djangoplicity.translation.fields.TranslationForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.image', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=djangoplicity.translation.fields.TranslationForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, limit_choices_to={'source__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='blog.post', verbose_name='Translation source'),
        ),
    ]
